data:
  root_dir: ./data
  calendar: "GENERIC"
  roll_rule: "open_interest"
  roll_days_before: 5
  continuous_method: "stitch_returns"
  prefer: synthetic

universe:
  # The examples generator makes 8 synthetic instruments across 4 sectors
  assets_file: ./configs/universe.yaml

signals:
  momentum:
    lookbacks: [63, 126, 252]
    skip_last_n: 20
    weight: 1.0

risk:
  vol_model: "ewma"
  vol_lookback: 63
  min_vol_periods: 20
  ewma_lambda: 0.94
  target_portfolio_vol: 0.15
  gross_exposure_limit: 2.5
  rebalance_threshold: 0.25
  risk_allocator: "proportional"
  max_instrument_vol_weight: 0.04
  sector_caps: {Rates: 0.4, Equities: 0.4, Commodities: 0.4, FX: 0.4}

execution:
  order_type: "market_next_open"
  adv_limit_pct: 0.2
  commission_per_contract: 2.5
  impact:
    model: "participation"
    k: 0.05
    alpha: 0.5
  min_slippage_ticks: 0.5
  tick_value: 10.0

backtest:
  start: "2010-01-01"
  starting_nav: 1000000.0
  end: "2020-12-31"
  rebalance: "daily"
  seed: 42
  results_dir: "./results"
